---
- hosts: container_with_cert
  gather_facts: no
  connection: local

  vars:
    certificate: ./files/ssl/differs.pem

  tasks:
    - name: Test update certificate with backup.
      smpcert:
        certificate: '{{certificate}}'
        backup: /tmp
